version: "3"

services:
  db:
    container_name: db
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - work
  api_work:
    container_name: api_work
    build: ./api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8005"
    depends_on:
      - db
    volumes:
      - ./api:/user/api
    ports:
      - "8005:8005"
    networks:
      - work
  client:
    container_name: client
    build: ./client
    ports:
      - "8080:8080"
    command: bash -c "yarn dev"
    depends_on:
      - api_work
    networks:
      - work
networks:
  work:
    external:
      name: work
