name: CI/CD Api

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
      container_name: db
      restart: always
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: myproject
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
    steps:
      - uses: actions/checkout@v2

      - name: setup node enviroment
        uses: actions/setup-node@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: api
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Test with Django
        working-directory: api
        run: |
          python manage.py test
