name: CI/CD Api

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: myproject
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: setup node enviroment
        uses: actions/setup-node@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        working-directory: api
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Test with Django
        working-directory: api
        run: |
          python manage.py migrate
          python manage.py test

      - name: Generate Coverage
        working-directory: api
        run: |
          coverage run --source='.' manage.py test
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./api/coverage.xml
          flags: backend
          fail_ci_if_error: true
