name: CI/CD Client

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup node enviroment
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Tests
        working-directory: client
        run: |
          yarn 
          yarn test

      - name: Lint
        working-directory: client
        run: |
          yarn 
          yarn lint
